name: Pull Request Build
on:
  push:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/test.yml'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  Build-KRedis:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/versi-tech/arch-linux-libs
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: ./gradlew build
        shell: bash