name: Pull Request Build
on:
  push:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/test.yml'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  Build-KRedis:
    runs-on: bullseye
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Instal hiredis
        run: apt update && apt --assume-yes install libhiredis-dev
        shell: bash
      - name: Build
        run: ./gradlew build
        shell: bash